spring:
  config:
    import: classpath:application-secret.yml

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require

  data:
    redis:
      host: localhost
      port: 6379

safepaw:
  jwt:
    access-expiration-minutes: 30
    refresh-expiration-days: 14